# Generated by Django 4.2 on 2023-05-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('security', models.CharField(choices=[('WPA', 'WPA'), ('WEP', 'WEP'), ('nopass', 'nopass')], max_length=6)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
